
# Site settings
github: [metadata]
title: Workers' Center at Stout United
description: >-
  An independent organization at UW Stout partnering with our educator's
  union to improve conditions for all workers and student.
logo: /assets/img/logo.png
baseurl: "/wc-at-su"
url: "https://olliebrown.github.io"

email: workerscenteratstoutunited@gmail.com
# twitter_username: jekyllrb
# github_username: jekyll

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
